* Visualização e tratamento

In [1]:
import pandas as pd
import numpy as np


df = pd.read_csv('../data/dados_saude_mental_fake.csv')

df.head()

,id_paciente,idade,genero,estado_civil,nivel_escolaridade,diagnostico_principal,nivel_estresse_0_10,horas_sono_media,uso_medicacao,numero_consultas_ano,faltas_consulta,satisfacao_tratamento_1_5,data_primeira_consulta
0,1,30,Feminino,Solteiro,Graduação,TEPT,0,5.5,Sim,2,3,5,2025-05-10
1,2,39,Feminino,Viúvo,Graduação,Burnout,7,6.0,Sim,4,2,1,2025-11-10
2,3,60,Masculino,Casado,Ensino Médio,TEPT,0,9.5,Não,6,0,3,2023-05-02
3,4,54,Feminino,Divorciado,Graduação,Burnout,1,6.0,Sim,5,0,4,2024-04-11
4,5,50,Masculino,Casado,Ensino Médio,Burnout,6,7.0,Sim,5,3,3,2023-11-27

In [2]:
df.shape

(2000, 13)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id_paciente                2000 non-null   int64
 1   idade                      2000 non-null   int64
 2   genero                     2000 non-null   object
 3   estado_civil               2000 non-null   object
 4   nivel_escolaridade         2000 non-null   object
 5   diagnostico_principal      2000 non-null   object
 6   nivel_estresse_0_10        2000 non-null   int64
 7   horas_sono_media           2000 non-null   float64
 8   uso_medicacao              2000 non-null   object
 9   numero_consultas_ano       2000 non-null   int64
 10  faltas_consulta            2000 non-null   int64
 11  satisfacao_tratamento_1_5  2000 non-null   int64
 12  data_primeira_consulta     2000 non-null   object
dtypes: float64(1), int64(6), object(6)
memory usage: 203.3+ KB

In [4]:
df.describe().round(2)

,id_paciente,idade,nivel_estresse_0_10,horas_sono_media,numero_consultas_ano,faltas_consulta,satisfacao_tratamento_1_5
count,2000.00,2000.00,2000.00,2000.00,2000.00,2000.00,2000.00
mean,1000.50,43.66,5.01,6.52,6.07,1.49,3.04
std,577.49,14.91,3.12,1.47,2.52,1.22,1.38
min,1.00,18.00,0.00,3.00,0.00,0.00,1.00
25%,500.75,31.00,2.00,5.50,4.00,1.00,2.00
50%,1000.50,44.00,5.00,6.50,6.00,1.00,3.00
75%,1500.25,57.00,8.00,7.50,8.00,2.00,4.00
max,2000.00,69.00,10.00,10.00,17.00,7.00,5.00

In [5]:
df.isnull().sum()

id_paciente                  0
idade                        0
genero                       0
estado_civil                 0
nivel_escolaridade           0
diagnostico_principal        0
nivel_estresse_0_10          0
horas_sono_media             0
uso_medicacao                0
numero_consultas_ano         0
faltas_consulta              0
satisfacao_tratamento_1_5    0
data_primeira_consulta       0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)